version: '3'

services:
  client:
    container_name: client
    restart: always
    build: ./client
    depends_on:
      - server

  server:
    container_name: server
    restart: always
    build: ./server
    env_file: variables.env
    volumes:
      - ./songs:/server/songs
      - ./artworks:/server/artworks
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    env_file: variables.env
    volumes:
      - ./server/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    container_name: nginx
    image:  nginx
    ports: 
      - 8080:8080
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - server
      - client
